import React, { useEffect, useState } from 'react';
import { Alert, SafeAreaView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { getAccessToken } from './src/api/secure';
import { getRoutes, getStops, getUniversities, login, startTrip, endTrip, saveSubscription, getNotifications, getActiveTrip, getLatestLocation } from './src/api/client';
import { publishCurrentLocation } from './src/background/driverLocation';
import { registerPushWithBackend } from './src/notifications/registerPush';
import { startBackgroundDriverLocation, stopBackgroundDriverLocation } from './src/background/backgroundLocation';
import { AdminDashboard } from './src/admin/AdminDashboard';

const languages = ['English', 'తెలుగు', 'हिन्दी'];

export default function App() {
  const [language, setLanguage] = useState('English');
  const [screen, setScreen] = useState<'language'|'login'|'student'|'driver'|'admin'>('language');
  const [email, setEmail] = useState('student@test.com');
  const [password, setPassword] = useState('student123');
  const [lead, setLead] = useState(10);
  const [tripStarted, setTripStarted] = useState(false);
  const [catalog, setCatalog] = useState('Loading university routes…');
  const [tripId, setTripId] = useState<string | null>(null);
  const [driverId, setDriverId] = useState<string | null>(null);
  const [unread, setUnread] = useState(0);
  const [liveStatus, setLiveStatus] = useState('Waiting for a live trip');
  useEffect(() => { if(driverId) registerPushWithBackend().catch(()=>undefined); }, [driverId]);
  useEffect(() => { if(!tripStarted) { stopBackgroundDriverLocation().catch(()=>undefined); return; } startBackgroundDriverLocation().catch(error => Alert.alert('Background GPS unavailable',error instanceof Error ? error.message : 'Check location permissions')); return () => { stopBackgroundDriverLocation().catch(()=>undefined); }; }, [tripStarted]);
  const setAlarm = async () => { try { const token=await getAccessToken(); if(!token || !driverId) throw new Error('Sign in again'); await saveSubscription(token,driverId,'00000000-0000-0000-0000-000000000008',lead); Alert.alert('Alarm ready',`You will be alerted ${lead} minutes before the bus reaches your stop.`); } catch(error) { Alert.alert('Alarm failed',error instanceof Error ? error.message : 'Try again'); } };
  useEffect(() => { if (!tripId || !driverId) return; const timer=setInterval(() => publishCurrentLocation(tripId, driverId).catch(error => Alert.alert('GPS update failed', error instanceof Error ? error.message : 'Try again')), 10000); publishCurrentLocation(tripId, driverId).catch(()=>undefined); return () => clearInterval(timer); }, [tripId, driverId]);
  useEffect(() => { if (screen !== 'student' || !driverId) return; const tokenPromise=getAccessToken(); tokenPromise.then(token => { if (token) saveSubscription(token,driverId,'00000000-0000-0000-0000-000000000008',lead).catch(()=>undefined); }); }, [lead, screen, driverId]);
  useEffect(() => { if (screen !== 'student' || !driverId) return; const refresh=async()=>{ const token=await getAccessToken(); if(token) { const items=await getNotifications(token,driverId).catch(()=>[]); setUnread(items.filter(item=>!item.read).length); } }; refresh(); const timer=setInterval(refresh,15000); return ()=>clearInterval(timer); }, [screen,driverId]);
  useEffect(() => { if(screen!=='student') return; const refresh=async()=>{try{const token=await getAccessToken();if(!token)return;const trip=await getActiveTrip(token,'00000000-0000-0000-0000-000000000008');if(!trip.active||!trip.tripId){setLiveStatus('Waiting for a live trip');return;}const point=await getLatestLocation(token,trip.tripId);setLiveStatus(point.stale?'Bus location is stale':point.latitude===undefined?'Waiting for GPS':'Live bus: '+point.latitude.toFixed(5)+', '+point.longitude!.toFixed(5));}catch{setLiveStatus('Live tracking unavailable');}};refresh();const timer=setInterval(refresh,10000);return()=>clearInterval(timer);},[screen]);
  useEffect(() => { if (screen !== 'student') return; let active=true; (async()=>{ try { const token=await getAccessToken(); if(!token) return; const universities=await getUniversities(token); const university=universities[0]; if(!university) return; const routes=await getRoutes(token,university.id); const route=routes[0]; if(!route) return; const stops=await getStops(token,route.id); if(active) setCatalog(`${university.name} · ${route.name} · ${stops.length} stops loaded`); } catch(e) { if(active) setCatalog(e instanceof Error ? e.message : 'Catalog unavailable'); } })(); return ()=>{active=false}; }, [screen]);
  if (screen === 'admin') return <Shell><Text style={styles.kicker}>ADMIN OPERATIONS</Text><Text style={styles.title}>Transport overview.</Text><AdminDashboard/><TouchableOpacity onPress={() => setScreen('login')}><Text style={styles.link}>Sign out</Text></TouchableOpacity></Shell>;
  if (screen === 'login') return <Shell><Text style={styles.kicker}>SMART COLLEGE BUS</Text><Text style={styles.title}>Welcome back.</Text><Text style={styles.subtitle}>Sign in to your college transport account.</Text><TextInput autoCapitalize="none" value={email} onChangeText={setEmail} placeholder="College email" style={styles.input}/><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" style={styles.input}/><TouchableOpacity style={styles.primary} onPress={async () => { try { const result=await login(email,password); setDriverId(result.userId); setScreen(result.role==='DRIVER'?'driver':result.role==='ADMIN'?'admin':'student'); } catch(error) { Alert.alert('Sign-in failed', error instanceof Error ? error.message : 'Try again'); } }}><Text style={styles.primaryText}>Sign in</Text></TouchableOpacity><TouchableOpacity onPress={() => setScreen('language')}><Text style={styles.link}>Change language</Text></TouchableOpacity></Shell>;
  if (screen === 'student') return <Shell><Text style={styles.kicker}>STUDENT HOME</Text><Text style={styles.title}>Your bus, at a glance.</Text><Text style={styles.subtitle}>Route 8 · Demo College · Mothinagar boarding stop</Text><View style={styles.mapCard}><Text style={styles.busEmoji}>🚌</Text><Text style={styles.mapTitle}>Waiting for a live trip</Text><Text style={styles.mapText}>The driver phone will appear here when the trip starts.</Text></View><Text style={styles.sectionTitle}>Arrival alarm</Text><View style={styles.chips}>{[5,10,15].map(value => <TouchableOpacity key={value} onPress={() => setLead(value)} style={[styles.chip,value===lead&&styles.chipSelected]}><Text style={[styles.chipText,value===lead&&styles.chipSelectedText]}>{value} min</Text></TouchableOpacity>)}</View><TouchableOpacity style={styles.primary} onPress={() => Alert.alert('Alarm ready',`You will be alerted ${lead} minutes before the bus reaches Mothinagar.`)}><Text style={styles.primaryText}>Set {lead}-minute alarm</Text></TouchableOpacity><TouchableOpacity onPress={() => setScreen('login')}><Text style={styles.link}>Sign out</Text></TouchableOpacity></Shell>;
  if (screen === 'driver') return <Shell><Text style={styles.kicker}>DRIVER MODE</Text><Text style={styles.title}>Route 8 trip control.</Text><Text style={styles.subtitle}>GPS publishing is enabled only during an active trip.</Text><View style={styles.driverCard}><Text style={styles.statusLabel}>STATUS</Text><Text style={styles.status}>{tripStarted ? '● Trip active' : '○ Not started'}</Text><Text style={styles.mapText}>Location permission · Pending setup</Text></View><TouchableOpacity style={[styles.primary,tripStarted&&styles.danger]} onPress={() => setTripStarted(!tripStarted)}><Text style={styles.primaryText}>{tripStarted ? 'End trip' : 'Start Route 8 trip'}</Text></TouchableOpacity><TouchableOpacity onPress={() => setScreen('login')}><Text style={styles.link}>Sign out</Text></TouchableOpacity></Shell>;
  return <GestureHandlerRootView style={styles.root}>
    <StatusBar barStyle="dark-content" />
    <SafeAreaView style={styles.root}>
      <View style={styles.content}>
        <Text style={styles.kicker}>SMART COLLEGE BUS</Text>
        <Text style={styles.title}>Never miss your bus.</Text>
        <Text style={styles.subtitle}>Get a reliable arrival alarm for your boarding stop.</Text>
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Choose your language</Text>
          {languages.map(item => <TouchableOpacity key={item} accessibilityRole="button" onPress={() => setLanguage(item)} style={[styles.option, item === language && styles.selected]}><Text style={[styles.optionText, item === language && styles.selectedText]}>{item}</Text><Text style={styles.check}>{item === language ? '✓' : ''}</Text></TouchableOpacity>)}
        </View>
        <TouchableOpacity style={styles.primary} accessibilityRole="button" onPress={() => setScreen('login')}><Text style={styles.primaryText}>Continue</Text></TouchableOpacity>
      </View>
    </SafeAreaView>
  </GestureHandlerRootView>;
}

function Shell({children}:{children:React.ReactNode}) { return <GestureHandlerRootView style={styles.root}><StatusBar barStyle="dark-content"/><SafeAreaView style={styles.root}><View style={styles.content}>{children}</View></SafeAreaView></GestureHandlerRootView>; }

const styles = StyleSheet.create({root:{flex:1,backgroundColor:'#f5f8f7'},content:{flex:1,padding:24,justifyContent:'center'},kicker:{color:'#00a878',fontSize:12,fontWeight:'800',letterSpacing:2},title:{color:'#0b1714',fontSize:38,fontWeight:'900',marginTop:14,lineHeight:44},subtitle:{color:'#64736e',fontSize:16,lineHeight:24,marginTop:12,marginBottom:32},card:{backgroundColor:'#fff',borderRadius:24,padding:18,shadowColor:'#000',shadowOpacity:.06,shadowRadius:18,elevation:3},cardTitle:{fontSize:18,fontWeight:'800',color:'#15221f',marginBottom:12},option:{minHeight:54,borderRadius:14,borderWidth:1,borderColor:'#e0e8e4',paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:10},selected:{backgroundColor:'#e4f7ef',borderColor:'#00a878'},optionText:{fontSize:16,color:'#30413b',fontWeight:'600'},selectedText:{color:'#08764f'},check:{fontSize:20,color:'#00a878',fontWeight:'900'},primary:{height:56,borderRadius:16,backgroundColor:'#00a878',alignItems:'center',justifyContent:'center',marginTop:24},danger:{backgroundColor:'#d94b4b'},primaryText:{color:'#fff',fontSize:17,fontWeight:'800'},input:{height:56,borderRadius:14,borderWidth:1,borderColor:'#d8e3de',backgroundColor:'#fff',paddingHorizontal:16,fontSize:16,marginTop:12},link:{textAlign:'center',color:'#08764f',fontWeight:'700',fontSize:15,marginTop:22},mapCard:{backgroundColor:'#e1f4ec',borderRadius:24,padding:24,alignItems:'center',marginBottom:26},busEmoji:{fontSize:46},mapTitle:{color:'#15352a',fontSize:20,fontWeight:'800',marginTop:10},mapText:{color:'#61736b',fontSize:14,lineHeight:21,marginTop:8,textAlign:'center'},sectionTitle:{color:'#15221f',fontSize:20,fontWeight:'800',marginBottom:10},chips:{flexDirection:'row',gap:10},chip:{paddingHorizontal:18,paddingVertical:12,borderRadius:20,borderWidth:1,borderColor:'#d8e3de'},chipSelected:{backgroundColor:'#00a878',borderColor:'#00a878'},chipText:{color:'#355148',fontWeight:'700'},chipSelectedText:{color:'#fff'},driverCard:{backgroundColor:'#fff',borderRadius:22,padding:22,elevation:2,marginBottom:16},statusLabel:{fontSize:11,color:'#6b7b74',fontWeight:'800',letterSpacing:1.5},status:{fontSize:24,color:'#15352a',fontWeight:'800',marginTop:8}});
